### ISSUE TITLE
请问有hi3798mv300的配置么

### ISSUE THREAD

**Issue by Dreamkeeper666** [glinuz/hi3798mv100#5]
我看到文档里有关于支持hi3798mv300的内容，但是我在config里并没有看到相关配置。请问有地方可以下载吗，谢谢！ @glinuz

**Comment by glinuz** [comment]
文档是官方文档。此版内核版本应该支持。我没有相关芯片，需要你自己研究一下。

**Comment by Dreamkeeper666** [comment]
> 文档是官方文档。此版内核版本应该支持。我没有相关芯片，需要你自己研究一下。
@glinuz 请问这个是最新的sdk么。因为我在config里没有看到mv300的配置。正常应该是都包含的？

**Comment by Dreamkeeper666** [comment]
@glinuz 请问这个是最新的sdk么。因为我在config里没有看到mv300的配置。正常应该是都包含的？还是说需要自己修改配置。这就是这一步操作的configs目录下的hi3798芯片里的各种型号
`cp configs/hi3798mv100/hi3798mdmo1g_hi3798mv100_cfg.mak ./cfg.mak
`

**Comment by glinuz** [comment]
不是最新的SDK.没有mv300那可能不支持。-------- 原始邮件 --------发件人： Dreamkeeper666 ***@***.***>日期： 2021年8月17日周二 17:38收件人： glinuz/hi3798mv100 ***@***.***>抄送： glin ***@***.***>, Mention ***@***.***>主    题： Re: [glinuz/hi3798mv100] 请问有hi3798mv300的配置么 (#5)

@glinuz 请问这个是最新的sdk么。因为我在config里没有看到mv300的配置。正常应该是都包含的？还是说需要自己修改配置。

**Comment by glinuz** [comment]
适配mv100 mv200的sdk。你需要再找找其他版本sdk-------- 原始邮件 --------发件人： Dreamkeeper666 ***@***.***>日期： 2021年8月17日周二 17:38收件人： glinuz/hi3798mv100 ***@***.***>抄送： glin ***@***.***>, Mention ***@***.***>主    题： Re: [glinuz/hi3798mv100] 请问有hi3798mv300的配置么 (#5)

@glinuz 请问这个是最新的sdk么。因为我在config里没有看到mv300的配置。正常应该是都包含的？还是说需要自己修改配置。
