### ISSUE TITLE
烧写设备和默认壁纸的问题

### ISSUE THREAD

**Issue by ifq** [glinuz/hi3798mv100#6]
你好，

请教两个问题
1、烧写是用串口就搞定了吗，还需要其他设备吗。
2、我现在拿到的这个盒子是个定制版本，这个版本的安卓桌面壁纸是一个我想删除的壁纸。 但是手工替换壁纸后，有时候系统会自行恢复出厂，这样原来的壁纸又展示出来了。我想删掉这个默认系统里的壁纸，不知道有没有什么方法。

感谢。

**Comment by glinuz** [comment]
这个项目是烧录Linux系统，纯Linux。不适合你的需求-------- 原始邮件 --------发件人： ifq ***@***.***>日期： 2021年11月11日周四 17:53收件人： glinuz/hi3798mv100 ***@***.***>抄送： Subscribed ***@***.***>主    题： [glinuz/hi3798mv100] 烧写设备和默认壁纸的问题 (Issue #6)
你好，
请教两个问题
1、烧写是用串口就搞定了吗，还需要其他设备吗。
2、我现在拿到的这个盒子是个定制版本，这个版本的安卓桌面壁纸是一个我想删除的壁纸。 但是手工替换壁纸后，有时候系统会自行恢复出厂，这样原来的壁纸又展示出来了。我想删掉这个默认系统里的壁纸，不知道有没有什么方法。
感谢。

**Comment by ifq** [comment]
我的设备连接串口，有打印 但是输入无响应， 请问是固件的问题吗？

**Comment by glinuz** [comment]
检查串口链接参数，115200 -------- 原始邮件 --------发件人： ifq ***@***.***>日期： 2021年11月11日周四 22:08收件人： glinuz/hi3798mv100 ***@***.***>抄送： glin ***@***.***>, Comment ***@***.***>主    题： Re: [glinuz/hi3798mv100] 烧写设备和默认壁纸的问题 (Issue #6)

我的设备连接串口，有打印 但是输入无响应， 请问是固件的问题吗？

**Comment by Dimselot** [comment]
你们编译内核都通过了吗？
我的在make fs 那里报错了，说我的rootfs太大了，那里规定最大是128M

**Comment by glinuz** [comment]
bootarg 有定义大小，同时烧录时的分区配置大小，两个要对上。-------- 原始邮件 --------发件人： massagemeli88 ***@***.***>日期： 2021年11月19日周五 00:59收件人： glinuz/hi3798mv100 ***@***.***>抄送： glin ***@***.***>, Comment ***@***.***>主    题： Re: [glinuz/hi3798mv100] 烧写设备和默认壁纸的问题 (Issue #6)

你们编译内核都通过了吗？

我的在make fs 那里报错了，说我的rootfs太大了，那里规定最大是128M
